version: '3'
name: eng-bot
services:
  bot:
    container_name: Eng-Bot
    image: eng-bot-bot
    restart: always
    depends_on:
      - tts-model
      - azure-sql-server
    env_file: .env
    environment:
      ENVIRONMENT: Production
      CONNECTION_STRING: $CONNECTION_STRING    
      # NEURAL_MODEL_HOST: http://tts-tacotron2:8000
      NEURAL_MODEL_HOST: http://tts-nemo:8000
      BOT_TOKEN: $BOT_TOKEN
      OPEN_AI_TOKEN: $OPEN_AI_TOKEN
    volumes:
      - /mnt/sdb/EngBot/logs:/app/logs


  tts-model:
    container_name: tts-nemo
    image: al1fe/eng-bot-nemo
    restart: always
    ports:
      - 8055:8000

  azure-sql-server:
    container_name: mnemonics-sql-db
    image: "mcr.microsoft.com/azure-sql-edge"
    restart: always
    ports:
      - "1455:1433"
    environment:
      - SA_PASSWORD=DZVW2cBqzfYAaHwAPhEg
      - ACCEPT_EULA=Y
    volumes:
      - /mnt/sdb/EngBot/TelegramEngBot_DB:/var/opt/mssql/data
           
volumes:
  eng_bot_db_data:
