version: '3'
name: eng-bot
services:
  azure-sql-server:
    container_name: mnemonics-sql-db
    image: "mcr.microsoft.com/azure-sql-edge"
    restart: always
    ports:
      - "1455:1433"
    environment:
      - SA_PASSWORD=DZVW2cBqzfYAaHwAPhEg
      - ACCEPT_EULA=Y
    volumes:
      - type: bind
        source: ..\TelegramEngBot_DB
        target: /var/opt/mssql/data
        
  tts-model:
    container_name: tts-tacotron2
    build: ../Tacotron2
    restart: always
    ports:
      - 8055:8000
      
  bot:
    container_name: Eng-Bot
    build: ../TelegramEngBot
    restart: always
    depends_on:
      - tts-model
      - azure-sql-server
    environment:
      ENVIRONMENT: Production
      CONNECTION_STRING: Server=azure-sql-server;Database=Mnemonics;User ID=sa;Password=DZVW2cBqzfYAaHwAPhEg;Integrated Security=False;TrustServerCertificate=True;MultipleActiveResultSets=true;      
      NEURAL_MODEL_HOST: http://tts-tacotron2:8000
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ../logs:/app/logs

volumes:
  eng_bot_db_data:
