version: '3'
services:
  azure-sql-server:
    container_name: Mnemonics-sql-db
    image: "mcr.microsoft.com/azure-sql-edge"    
    ports:
      - "1444:1433"
    environment:
      - SA_PASSWORD=DZVW2cBqzfYAaHwAPhEg
      - ACCEPT_EULA=Y
    volumes:
      - type: bind
        source: C:\TelegramEngBot_DB
        target: /var/opt/mssql/data

volumes:
  telegram_eng_bot_db_data:
