name: Deploy to Server

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH into server, down containers and delete image
      uses: appleboy/ssh-action@master
      with:
        host: 185.162.21.198 # ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ../../deploy
          docker-compose down
    # docker image rm al1fe/eng-bot-bot

    # - name: Build Docker images
      # run: |        
        # docker build -t al1fe/eng-bot-bot -f ../TelegramEngBot/Dockerfile .       
        # if ! docker image inspect al1fe/eng-bot-tts-model; then
          # docker build -t al1fe/eng-bot-tts-model -f ../Tacotron2/Dockerfile .
        # fi
        
    # - name: SSH into server and run containers
      # uses: appleboy/ssh-action@master
      # with:
        # host: ${{ secrets.SERVER_HOST }}
        # username: ${{ secrets.SERVER_USERNAME }}
        # password: ${{ secrets.SERVER_PASSWORD }}
        # script: |
          # docker-compose up -d
          