name: Deploy to Server

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker images
      run: |        
        docker build -t al1fe/eng-bot -f TelegramEngBot/Dockerfile .
      
        # if ! docker image inspect al1fe/tacotron2-model; then
          # docker build -t al1fe/tacotron2-model -f ../Tacotron2/Dockerfile .
        # fi
        
    - name: SSH into server, down containers and delete image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker compose pull
          docker compose up


        
          # docker compose down
          # docker image rm al1fe/eng-bot
          # docker compose pull
          # docker compose up
          